name: Publish Typedoc to Github Pages
on:
    push:
        branches:
            - main
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"

            - name: Install
              run: npm install

            - name: Typedoc
              run: npx typedoc src/lanzou.ts src/types.ts --out ./doc

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./doc
